1).使用virtualenv时注意python环境变量，可能启动服务时报导入包的错。曾尝试过把当前项目路径加入环境变量未能成功，所以在manage.py里改变了sys.path。

2).settings.py中数据库信息修改

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', #'django.db.backends.',  # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'tmitter',  # Or path to database file if using sqlite3.
        'USER': 'yuyuan',  # Not used with sqlite3.
        'PASSWORD': 'yuyuan',  # Not used with sqlite3.
        'HOST': '127.0.0.1',  # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '5432',  # Set to empty string for default. Not used with sqlite3.
    }
}


3).启动服务成功后，注册遇到报错。因为注册时默认用户area的id为1.但area表中无数据。先在area表中增加一条数据。

4).适配手机访问。


